version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: weather-db
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NAVER_MAPS_CLIENT_ID=${VUE_APP_NAVER_MAPS_CLIENT_ID}
        - API_BASE_URL=${VUE_APP_API_BASE_URL:-http://localhost:8080}
    container_name: weather-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=weatherdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=yourpassword
      - WEATHER_API_KEY=${WEATHER_API_KEY:-your-default-key}
    restart: unless-stopped

volumes:
  postgres_data: