server:
  port: 8080

spring:
  application:
    name: weather-app
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s

weather:
  api:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    key: ${WEATHER_API_KEY:YOUR_WEATHER_API_KEY}

naver:
  map:
    client-id: ${NAVER_CLIENT_ID:YOUR_NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET:YOUR_NAVER_CLIENT_SECRET}

logging:
  level:
    com.example.weather: DEBUG
    org.springframework.web: INFO
